### ISSUE TITLE
tar output files to speed up uploading

### ISSUE THREAD

**Issue by jethror1** [eastgenomics/eggd_cgppindel#2]
- App outputs over 500 files, all but 8 of these are small log files and takes ~25 minutes to upload (1/4 -1/3 of total run time).
- This could be reduced to less than a minute by first tarring all log files and uploading as a single file

**Comment by JasonLing95** [comment]
added in [v1.0.1](https://github.com/eastgenomics/eggd_cgppindel/releases/tag/v1.0.1)
